#	***************************************************
#		^> File Name: makefile
#		^> Author: AoEiuV020
#		^> Mail: 490674483@qq.com
#		^> Created Time: 2015/11/02 - 14:49:08
#	***************************************************
all:
	chgrp tty talk
	chmod u+s,g+s talk
